nameB = ord('B')
print(nameB)
nameC = ord('C')
print(nameC)
nameD = ord('D')
print(nameD)
nameb = ord('b')
print(nameb)
namec = ord('c')
print(namec)
named = ord('d')
print(named)
name0 = ord('0')
print(name0)
name1 = ord('1')
print(name1)
name2 = ord('2')
print(name2)
name_dollar = ord('$')
print(name_dollar)
name_multiply = ord('*')
print(name_multiply)
name_addition = ord('+')
print(name_addition)
name_space = ord(' ')
print(name_space)